version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rpassistant
      POSTGRES_USER: rpassistant
      POSTGRES_PASSWORD: rpassistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpassistant"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: